#!/usr/bin/env bash

set -e

REPO_DIR=$(dirname $( cd $(dirname $0) && pwd ))

SUITE=$1
shift
TEST=$1
shift
export VERILATOR_ROOT=$REPO_DIR/$1
shift
export PATH="$VERILATOR_ROOT/bin:$PATH"

TEST_FILE=$REPO_DIR/tests/$SUITE/$TEST

UVM_DIR=$REPO_DIR/uvm/src

OUT_DIR=$REPO_DIR/out/$SUITE/uvm
mkdir -p $OUT_DIR

verilator --binary $UVM_DIR/uvm.sv -I$UVM_DIR $TEST_FILE -Mdir $OUT_DIR --timing --DUVM_NO_DPI -Wno-lint -Wno-style -Wno-CONSTRAINTIGN -Wno-ZERODLY -Wno-SYMRSVDWORD --build-jobs `nproc` --prefix Vtop $@
timeout 100 $OUT_DIR/Vtop
